name: derrybirkett
favicon: null
layout_spectrum: 0.6458417398389429
typography_spectrum: 0.36079996498301625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.29471140820533037
  lightness: 0.6890439924318343
  saturation: 0.492791342549026
  rhythmicContrast: 0.05970863625407219
purpose: []
